#!/bin/bash
# PulseAudio Virtual Audio Setup for Thoth Voice Assistant
# This script sets up virtual audio devices for routing TTS output to voice calls on Linux

set -e

echo "=========================================="
echo "Thoth Voice Assistant - PulseAudio Setup"
echo "=========================================="
echo ""

# Check if PulseAudio is running
if ! pgrep -x "pulseaudio" > /dev/null; then
    echo "❌ ERROR: PulseAudio is not running!"
    echo "   Please start PulseAudio first:"
    echo "   pulseaudio --start"
    exit 1
fi

echo "✓ PulseAudio is running"
echo ""

# Check if pactl is available
if ! command -v pactl &> /dev/null; then
    echo "❌ ERROR: pactl command not found!"
    echo "   Please install PulseAudio utilities:"
    echo "   sudo apt-get install pulseaudio-utils"
    exit 1
fi

echo "✓ pactl is available"
echo ""

# Function to check if a module is already loaded
module_exists() {
    pactl list modules short | grep -q "$1"
}

# Function to get module ID
get_module_id() {
    pactl list modules short | grep "$1" | awk '{print $1}'
}

echo "Setting up virtual audio devices..."
echo ""

# 1. Create virtual speaker (null sink for TTS output)
VIRTUAL_SPEAKER_NAME="virtual_speaker"
VIRTUAL_SPEAKER_DESC="Thoth_Virtual_Speaker"

if module_exists "sink_name=${VIRTUAL_SPEAKER_NAME}"; then
    echo "⚠ Virtual speaker already exists, unloading..."
    MODULE_ID=$(get_module_id "sink_name=${VIRTUAL_SPEAKER_NAME}")
    pactl unload-module "$MODULE_ID"
fi

echo "Creating virtual speaker: ${VIRTUAL_SPEAKER_NAME}"
pactl load-module module-null-sink \
    sink_name="${VIRTUAL_SPEAKER_NAME}" \
    sink_properties=device.description="${VIRTUAL_SPEAKER_DESC}"

echo "✓ Virtual speaker created: ${VIRTUAL_SPEAKER_NAME}"
echo ""

# 2. List available output devices (where calls might be)
echo "Available output devices for call routing:"
echo "=========================================="
pactl list sinks short | nl
echo ""

# 3. Prompt user to select the device for their voice calls
echo "Which device is used for your voice calls?"
echo "Enter the number from the list above (or press Enter to skip loopback setup):"
read -r DEVICE_NUMBER

if [ -n "$DEVICE_NUMBER" ]; then
    # Get the sink name from the selected number
    CALL_SINK=$(pactl list sinks short | sed -n "${DEVICE_NUMBER}p" | awk '{print $2}')

    if [ -n "$CALL_SINK" ]; then
        echo ""
        echo "Creating loopback: ${VIRTUAL_SPEAKER_NAME} → ${CALL_SINK}"

        # Remove existing loopback if it exists
        if module_exists "source=${VIRTUAL_SPEAKER_NAME}.monitor"; then
            echo "⚠ Removing existing loopback..."
            MODULE_ID=$(get_module_id "source=${VIRTUAL_SPEAKER_NAME}.monitor")
            pactl unload-module "$MODULE_ID"
        fi

        # Create loopback from virtual speaker to call device
        pactl load-module module-loopback \
            source="${VIRTUAL_SPEAKER_NAME}.monitor" \
            sink="${CALL_SINK}" \
            latency_msec=1

        echo "✓ Loopback created successfully"
    else
        echo "❌ Invalid device number"
        exit 1
    fi
else
    echo "⚠ Skipping loopback setup. You can create it manually later with:"
    echo "  pactl load-module module-loopback source=${VIRTUAL_SPEAKER_NAME}.monitor sink=<your_call_sink>"
fi

echo ""
echo "=========================================="
echo "✓ PulseAudio setup complete!"
echo "=========================================="
echo ""
echo "Configuration summary:"
echo "  - Virtual speaker: ${VIRTUAL_SPEAKER_NAME}"
echo "  - TTS output device: ${VIRTUAL_SPEAKER_NAME}"
echo ""
echo "Next steps:"
echo "  1. Set TTS_OUTPUT_DEVICE=${VIRTUAL_SPEAKER_NAME} in your .env file"
echo "  2. Run: python thoth/backend/core/call_assistant/app_v3.py"
echo ""

# Offer to make persistent
echo "=========================================="
echo "Make this setup persistent? (y/n)"
echo "This will automatically load on system startup"
read -r MAKE_PERSISTENT

if [ "$MAKE_PERSISTENT" = "y" ] || [ "$MAKE_PERSISTENT" = "Y" ]; then
    PULSE_CONFIG="$HOME/.config/pulse/default.pa"

    # Create config directory if it doesn't exist
    mkdir -p "$HOME/.config/pulse"

    # Create or append to default.pa
    if [ ! -f "$PULSE_CONFIG" ]; then
        echo "# PulseAudio configuration - auto-generated by Thoth setup" > "$PULSE_CONFIG"
        echo ".include /etc/pulse/default.pa" >> "$PULSE_CONFIG"
        echo "" >> "$PULSE_CONFIG"
    fi

    # Check if our config already exists
    if ! grep -q "# Thoth Voice Assistant" "$PULSE_CONFIG"; then
        echo "" >> "$PULSE_CONFIG"
        echo "# Thoth Voice Assistant - Virtual Audio Devices" >> "$PULSE_CONFIG"
        echo "load-module module-null-sink sink_name=${VIRTUAL_SPEAKER_NAME} sink_properties=device.description=${VIRTUAL_SPEAKER_DESC}" >> "$PULSE_CONFIG"

        if [ -n "$CALL_SINK" ]; then
            echo "load-module module-loopback source=${VIRTUAL_SPEAKER_NAME}.monitor sink=${CALL_SINK} latency_msec=1" >> "$PULSE_CONFIG"
        fi

        echo "✓ Configuration saved to: $PULSE_CONFIG"
        echo "  Virtual audio will be available after reboot or running: pulseaudio -k && pulseaudio --start"
    else
        echo "⚠ Configuration already exists in $PULSE_CONFIG"
    fi
else
    echo "⚠ Setup is temporary. Run this script again after reboot."
fi

echo ""
echo "=========================================="
echo "Setup complete! Happy calling!"
echo "=========================================="
